// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.6.0.0
//    <NameSpace>YalvLib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>True</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

namespace YalvLib.Infrastructure.Log4Net
{
    public partial class Event
    {

        [XmlElement("message")]
        public string Message { get; set; }
        [XmlElement("NDC")]
        public string NDC { get; set; }
        [XmlElement("throwable")]
        public string Throwable { get; set; }
        [XmlElement("locationInfo")]
        public LocationInfo LocationInfo { get; set; }
        [XmlArray("properties")]
        [XmlArrayItem("data")]
        public List<Data> Properties { get; set; }
        [XmlAttribute("logger")]
        public string Logger { get; set; }
        [XmlAttribute("timestamp")]
        public string Timestamp { get; set; }
        [XmlAttribute("level")]
        public string Level { get; set; }
        [XmlAttribute("thread")]
        public string Thread { get; set; }

        public Event()
        {
            this.Properties = new List<Data>();
            this.LocationInfo = new LocationInfo();
        }
    }

    public partial class LocationInfo
    {

        [XmlAttribute("class")]
        public string Class { get; set; }
        [XmlAttribute("method")]
        public string Method { get; set; }
        [XmlAttribute("file")]
        public string File { get; set; }
        [XmlAttribute("line")]
        public string Line { get; set; }
    }

    public partial class Data
    {
        [XmlAttribute("name")]
        public string Name { get; set; }
        [XmlAttribute("value")]
        public string Value { get; set; }
    }

    public partial class Properties
    {

        public List<Data> Data { get; set; }

        public Properties()
        {
            this.Data = new List<Data>();
        }
    }
}
